version: '3.7'

services:

  postgres:
    image: postgres:13-alpine
    restart: 'no'
    volumes:
      - ${DATABASE_PATH}:/database
      - ./config/db-init:/docker-entrypoint-initdb.d/
    environment:
      TZ: UTC-8
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /database
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 -E UTF8
