

version: '3.7'

services:

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: 'no'
    volumes:
      - ${DATABASE_PATH}:/database
      - ./data/reserve:/docker-entrypoint-initdb.d/
    environment:
      TZ: UTC-8
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /database
      POSTGRES_INITDB_ARGS: -E UTF8 --auth-host=scram-sha-256
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256

