

version: '3.7'

services:

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: 'no'
    volumes:
      - ${DATABASE_PATH}:/database
      - ./data/reserve:/reserve
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      PGDATA: /database
    command: su postgres -c "pg_ctl start && pg_dumpall > /reserve/reserve.sql"

