version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ${DB_PATH}:/database
    environment:
      TZ: UTC-8
      PGDATA: /database
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}